api = "0.2"

[buildpack]
  id = "paketo-buildpacks/yarn-install"
  name = "Paketo Yarn Install Buildpack"
  homepage = "https://github.com/paketo-buildpacks/yarn-install"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
